# postgres-db-targeting-service
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-targeting-service
  labels:
    app: postgres-db-targeting-service
spec:
  containers:
    - name: postgres-db-targeting-service
      image: postgres:18.4-alpine3.24
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: targeting-service-secrets
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: targeting-service-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: targeting-service-secrets
              key: DB_DATABASE
      volumeMounts:
        - name: pgdata-targeting-service
          mountPath: /var/lib/postgresql
  volumes:
    - name: pgdata-targeting-service
      persistentVolumeClaim:
        claimName: pgdata-targeting-service-pvc


# ===========================================================================
# targeting-service
apiVersion: v1
kind: Pod
metadata:
  name: targeting-service
  labels:
    app: targeting-service
spec:
  containers:
    - name: targeting-service
      image: 798350130470.dkr.ecr.us-east-1.amazonaws.com/targeting-service:latest
      ports:
        - containerPort: 8003
      env:
        - name: PORT
          value: "8003"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: targeting-service-secrets
              key: DB_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: targeting-service-secrets
              key: AUTH_SERVICE_URL
    # Fazer dependencia (equivalente a depends_on no docker)
