apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-targeting-service
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  hostPath:
    path: /data/targeting-service/pgdata
    type: DirectoryOrCreate
