services:

# Analytics Service =================================================================
  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    build:
      context: ./analytics-service
    ports:
      - "8030:${PORT_ANALYTICS_SERVICE}"
    environment:
      PORT: ${PORT_ANALYTICS_SERVICE}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

# Auth Service =================================================================
  postgres-db-auth-service:
    container_name: postgres-db-auth-service
    image: postgres:18.4-alpine3.24
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_AUTH_SERVICE}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth-service:/var/lib/postgresql
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 2s
      timeout: 5s
      retries: 10

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build: 
      context: ./auth-service
    ports:
      - "8080:${PORT_AUTH_SERVICE}"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres-db-auth-service:5432/${DB_DATABASE_AUTH_SERVICE}
      MASTER_KEY: ${MASTER_KEY}
      PORT: ${PORT_AUTH_SERVICE}
    depends_on:
      postgres-db-auth-service:
        condition: service_healthy

# Evaluation Service =================================================================
  redis:
    container_name: redis
    image: redis:8.10-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 10

  evaluation-service:
    image: evaluation-service:latest
    container_name: evaluation-service
    build:
      context: ./evaluation-service
    ports:
      - "8060:${PORT_EVALUATION_SERVICE}"
    environment:
      PORT: ${PORT_EVALUATION_SERVICE}
      REDIS_URL: ${REDIS_URL}
      FLAG_SERVICE_URL: ${FLAG_SERVICE_URL}
      TARGETING_SERVICE_URL: ${TARGETING_SERVICE_URL}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    depends_on:
      redis:
        condition: service_healthy

# Flag Service =================================================================
  postgres-db-flag-service:
    container_name: postgres-db-flag-service
    image: postgres:18.4-alpine3.24
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_FLAG_SERVICE}
    ports:
      - "5434:5432"
    volumes:
      - pgdata-flag-service:/var/lib/postgresql
      - ./flag-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 2s
      timeout: 5s
      retries: 10

  flag-service:
    image: flag-service:latest
    container_name: flag-service
    build:
      context: ./flag-service
    ports:
      - "8090:${PORT_FLAG_SERVICE}"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres-db-flag-service:5432/${DB_DATABASE_FLAG_SERVICE}
      PORT: ${PORT_FLAG_SERVICE}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      postgres-db-flag-service:
        condition: service_healthy

# Targeting Service =================================================================
  postgres-db-targeting-service:
    container_name: postgres-db-targeting-service
    image: postgres:18.4-alpine3.24
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_TARGETING_SERVICE}
    ports:
      - "5435:5432"
    volumes:
      - pgdata-targeting-service:/var/lib/postgresql
      - ./targeting-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 2s
      timeout: 5s
      retries: 10

  targeting-service:
    image: targeting-service:latest
    container_name: targeting-service
    build:
      context: ./targeting-service
    ports:
      - "8073:${PORT_TARGETING_SERVICE}"
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres-db-targeting-service:5432/${DB_DATABASE_TARGETING_SERVICE}
      PORT: ${PORT_TARGETING_SERVICE}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    depends_on:
      postgres-db-targeting-service:
        condition: service_healthy

volumes:
  pgdata-auth-service:
  pgdata-flag-service:
  pgdata-targeting-service: