services:
  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    build: .
    ports:
      - "8030:${PORT}"
    environment:
      PORT: ${PORT}
      AWS_SQS_URL: ${AWS_SQS_URL}
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}