# postgres-db-flag-service
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db-flag-service
  namespace: flag-service
  labels:
    app: flag-service
    instance: postgres-db-flag-service
spec:
  containers:
    - name: postgres-db-flag-service
      image: postgres:18.4-alpine3.24
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-flag-service
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opaque-flag-service
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap-flag-service
              key: DB_DATABASE
      volumeMounts:
        - name: pgdata-flag-service
          mountPath: /var/lib/postgresql
  volumes:
    - name: pgdata-flag-service
      persistentVolumeClaim:
        claimName: pvc-pgdata-flag-service
