# redis-evaluation-service
apiVersion: v1
kind: Pod
metadata:
  name: redis-evaluation-service
  namespace: evaluation-service
  labels:
    app: evaluation-service
    instance: redis-evaluation-service
spec:
  containers:
    - name: redis-evaluation-service
      image: redis:8.10-alpine
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
      ports:
        - containerPort: 6379
