apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgdata-flag-service
  namespace: flag-service
  labels:
    app: pvc-pgdata-flag-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 50Mi
