apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-auth-service
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  hostPath:
    path: /data/auth-service/pgdata
    type: DirectoryOrCreate
