apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth-service
  namespace: auth-service
  labels:
    app: auth-service
    instance: app-auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
      instance: app-auth-service
  template:
    metadata:
      labels:
        app: auth-service
        instance: app-auth-service
    spec:
      containers:
        - name: auth-service
          # image: auth-service:local # Local
          image: 798350130470.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest # Nuvem
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
            - name: PORT
              value: "8001"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: opaque-auth-service
                  key: DB_URL
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: opaque-auth-service
                  key: MASTER_KEY
