apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgdata-auth-service
  namespace: auth-service
  labels:
    app: pvc-pgdata-auth-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 50Mi
