# dynamodb-local
apiVersion: v1
kind: Service
metadata:
  name: svc-dynamodb-local
  namespace: analytics-service
  labels:
    app: analytics-service
    instance: svc-dynamodb-local
spec:
  type: ClusterIP
  selector:
    app: analytics-service
    instance: dynamodb-local
  ports:
    - port: 8000
      targetPort: 8000


---
# analytics-service
apiVersion: v1
kind: Service
metadata:
  name: svc-analytics-service
  namespace: analytics-service
  labels:
    app: analytics-service
    instance: svc-analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
    instance: app-analytics-service
  ports:
    - port: 80
      targetPort: 8005
