apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-evaluation-service
  namespace: evaluation-service
data:
  REDIS_URL: "rediss://clustercfg.redis-evaluation-service.sy66yd.use2.cache.amazonaws.com:6379"
  FLAG_SERVICE_URL: "http://svc-flag-service.flag-service.svc.cluster.local:80"
  TARGETING_SERVICE_URL: "http://svc-targeting-service.targeting-service.svc.cluster.local:80"
  AWS_SQS_URL: "https://sqs.us-east-2.amazonaws.com/370930247065/sqs-analytics-service"
  AWS_REGION: "us-east-2"
